# This is the build script for the Carnalitas mod
# It creates the Carnalitas.mod file based on the descriptor.mod, and compresses it alongside the mod folder into a properly named archive

name: Build mod archive

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version'
        default: '*.*'
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    # Checkouts the repository into the building environment
    - uses: actions/checkout@v2
      with:
        path: Carnalitas
    
    # Creates the Carnalitas.mod file
    - run: cp ${{ github.workspace }}/Carnalitas/descriptor.mod ${{ github.workspace }}/Carnalitas.mod
    - run: echo -e '\npath="mod/Carnalitas"' >> Carnalitas.mod  
    
    # Compress the mod and upload the archive (the paths starting with ! are excluded from the archive)
    - uses: actions/upload-artifact@v2
      with:
        name: Carnalitas.${{ github.event.inputs.version }}
        path: |
          ${{ github.workspace }}
          !${{ github.workspace }}/Carnalitas/.git
          !${{ github.workspace }}/Carnalitas/.github
          !${{ github.workspace }}/Carnalitas/*.md
          !${{ github.workspace }}/Carnalitas/*.txt
